# Generated by Django 4.2.7 on 2026-01-09 20:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='External user identifier from the frontend', max_length=100)),
                ('user_email', models.EmailField(help_text='Email address of the user', max_length=254)),
                ('start_time', models.DateTimeField(help_text='When the conversation session started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the conversation session ended', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edital', models.ForeignKey(blank=True, help_text='The edital this conversation is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to='editals.edital')),
            ],
            options={
                'verbose_name': 'Conversation Session',
                'verbose_name_plural': 'Conversation Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], help_text='Whether this message is from the user or bot', max_length=10)),
                ('content', models.TextField(help_text='The message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edital', models.ForeignKey(blank=True, help_text='The edital this message is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='editals.edital')),
                ('session', models.ForeignKey(help_text='The conversation session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversationsession')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='conversatio_session_2f9f92_idx'), models.Index(fields=['role'], name='conversatio_role_095bb9_idx'), models.Index(fields=['edital'], name='conversatio_edital__1dc118_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user_email'], name='conversatio_user_em_021dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['start_time'], name='conversatio_start_t_73f46f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['edital'], name='conversatio_edital__cb5fb3_idx'),
        ),
    ]
