# Generated by Django 4.2.7 on 2026-01-09 19:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the edital', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the edital')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='draft', help_text='Current status of the edital', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('main_pdf', 'Main PDF'), ('annexe', 'Annexe'), ('result', 'Result')], help_text='Type of file attachment', max_length=20)),
                ('name', models.CharField(help_text='Display name for the file', max_length=255)),
                ('original_name', models.CharField(help_text='Original filename when uploaded', max_length=255)),
                ('url', models.URLField(blank=True, help_text='URL to access the file (for mock data or external storage)', validators=[django.core.validators.URLValidator()])),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edital', models.ForeignKey(help_text='The edital this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='editals.edital')),
            ],
            options={
                'verbose_name': 'Edital File',
                'verbose_name_plural': 'Edital Files',
                'ordering': ['file_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EditalMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Metadata key (e.g., 'deadline', 'budget', 'category')", max_length=100)),
                ('value', models.TextField(help_text='Metadata value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edital', models.ForeignKey(help_text='The edital this metadata belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='editals.edital')),
            ],
            options={
                'verbose_name': 'Edital Metadata',
                'verbose_name_plural': 'Edital Metadata',
                'ordering': ['key'],
                'unique_together': {('edital', 'key')},
            },
        ),
    ]
